//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_NewsTable_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_NewsTable_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\Usuario\AppData\Local\Temp\6271EE752E9C626B975EF5F159A90133834D\2\ProyectVDEradio\ProyectVDEradio\Views\News\NewsTable.cshtml"
  
    ViewBag.Title = "NewsTable";


#line default
#line hidden

#line 2 "C:\Users\Usuario\AppData\Local\Temp\6271EE752E9C626B975EF5F159A90133834D\2\ProyectVDEradio\ProyectVDEradio\Views\News\NewsTable.cshtml"
__o = model;


#line default
#line hidden

#line 3 "C:\Users\Usuario\AppData\Local\Temp\6271EE752E9C626B975EF5F159A90133834D\2\ProyectVDEradio\ProyectVDEradio\Views\News\NewsTable.cshtml"
                                            __o = Model?.Count() ?? 0;


#line default
#line hidden

#line 4 "C:\Users\Usuario\AppData\Local\Temp\6271EE752E9C626B975EF5F159A90133834D\2\ProyectVDEradio\ProyectVDEradio\Views\News\NewsTable.cshtml"
           __o = Html.ActionLink("➕ Crear Nueva Noticia", "Create", null, new { @class = "btn btn-primary" });


#line default
#line hidden

#line 5 "C:\Users\Usuario\AppData\Local\Temp\6271EE752E9C626B975EF5F159A90133834D\2\ProyectVDEradio\ProyectVDEradio\Views\News\NewsTable.cshtml"
                    foreach (var noticia in Model)
                    {
                        

#line default
#line hidden

#line 6 "C:\Users\Usuario\AppData\Local\Temp\6271EE752E9C626B975EF5F159A90133834D\2\ProyectVDEradio\ProyectVDEradio\Views\News\NewsTable.cshtml"
                                       __o = noticia.ArticleTitle;


#line default
#line hidden

#line 7 "C:\Users\Usuario\AppData\Local\Temp\6271EE752E9C626B975EF5F159A90133834D\2\ProyectVDEradio\ProyectVDEradio\Views\News\NewsTable.cshtml"
                                             __o = noticia.ArticleID;


#line default
#line hidden

#line 8 "C:\Users\Usuario\AppData\Local\Temp\6271EE752E9C626B975EF5F159A90133834D\2\ProyectVDEradio\ProyectVDEradio\Views\News\NewsTable.cshtml"
                           __o = noticia.Categories.CategoryName;


#line default
#line hidden

#line 9 "C:\Users\Usuario\AppData\Local\Temp\6271EE752E9C626B975EF5F159A90133834D\2\ProyectVDEradio\ProyectVDEradio\Views\News\NewsTable.cshtml"
                           __o = noticia.Users.UserName;


#line default
#line hidden

#line 10 "C:\Users\Usuario\AppData\Local\Temp\6271EE752E9C626B975EF5F159A90133834D\2\ProyectVDEradio\ProyectVDEradio\Views\News\NewsTable.cshtml"
                           __o = noticia.ArticleDate.ToShortDateString();


#line default
#line hidden

#line 11 "C:\Users\Usuario\AppData\Local\Temp\6271EE752E9C626B975EF5F159A90133834D\2\ProyectVDEradio\ProyectVDEradio\Views\News\NewsTable.cshtml"
                           __o = Html.ActionLink("✏️ Editar", "Edit", new { id = noticia.ArticleID }, new { @class = "btn btn-warning" });


#line default
#line hidden

#line 12 "C:\Users\Usuario\AppData\Local\Temp\6271EE752E9C626B975EF5F159A90133834D\2\ProyectVDEradio\ProyectVDEradio\Views\News\NewsTable.cshtml"
                           __o = Html.Raw($"<a href='#' class='action-btn btn-danger' onclick=\"showDeleteModal('{noticia.ArticleTitle}', '{noticia.ArticleID}')\">🗑️ Eliminar</a>");


#line default
#line hidden

#line 13 "C:\Users\Usuario\AppData\Local\Temp\6271EE752E9C626B975EF5F159A90133834D\2\ProyectVDEradio\ProyectVDEradio\Views\News\NewsTable.cshtml"
                             
                    }

#line default
#line hidden

#line 14 "C:\Users\Usuario\AppData\Local\Temp\6271EE752E9C626B975EF5F159A90133834D\2\ProyectVDEradio\ProyectVDEradio\Views\News\NewsTable.cshtml"
                    using (Html.BeginForm("DeleteConfirmed", "News", FormMethod.Post))
                    {
                        

#line default
#line hidden

#line 15 "C:\Users\Usuario\AppData\Local\Temp\6271EE752E9C626B975EF5F159A90133834D\2\ProyectVDEradio\ProyectVDEradio\Views\News\NewsTable.cshtml"
                   __o = Html.AntiForgeryToken();


#line default
#line hidden

#line 16 "C:\Users\Usuario\AppData\Local\Temp\6271EE752E9C626B975EF5F159A90133834D\2\ProyectVDEradio\ProyectVDEradio\Views\News\NewsTable.cshtml"
                                                
                        

#line default
#line hidden

#line 17 "C:\Users\Usuario\AppData\Local\Temp\6271EE752E9C626B975EF5F159A90133834D\2\ProyectVDEradio\ProyectVDEradio\Views\News\NewsTable.cshtml"
                                                                                   
                        

#line default
#line hidden

#line 18 "C:\Users\Usuario\AppData\Local\Temp\6271EE752E9C626B975EF5F159A90133834D\2\ProyectVDEradio\ProyectVDEradio\Views\News\NewsTable.cshtml"
                                 
                    }

#line default
#line hidden

#line 19 "C:\Users\Usuario\AppData\Local\Temp\6271EE752E9C626B975EF5F159A90133834D\2\ProyectVDEradio\ProyectVDEradio\Views\News\NewsTable.cshtml"
                __o = Url.Action("Index", "Management");


#line default
#line hidden
}
}
}
