//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\Lucas\AppData\Local\Temp\9A54D53D4AA3BCCBF86013B346DA31938DF1\2\ProyectVDEradio\ProyectVDEradio\Views\Home\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\Lucas\AppData\Local\Temp\9A54D53D4AA3BCCBF86013B346DA31938DF1\2\ProyectVDEradio\ProyectVDEradio\Views\Home\Index.cshtml"
  
    ViewBag.Title = "Home Page";


#line default
#line hidden

#line 3 "C:\Users\Lucas\AppData\Local\Temp\9A54D53D4AA3BCCBF86013B346DA31938DF1\2\ProyectVDEradio\ProyectVDEradio\Views\Home\Index.cshtml"
    if (Model.ProgramaEnVivo != null)
    {
        

#line default
#line hidden

#line 4 "C:\Users\Lucas\AppData\Local\Temp\9A54D53D4AA3BCCBF86013B346DA31938DF1\2\ProyectVDEradio\ProyectVDEradio\Views\Home\Index.cshtml"
                   = Model.ProgramaEnVivo.ProgramName;


#line default
#line hidden

#line 5 "C:\Users\Lucas\AppData\Local\Temp\9A54D53D4AA3BCCBF86013B346DA31938DF1\2\ProyectVDEradio\ProyectVDEradio\Views\Home\Index.cshtml"
                  = Model.ProgramaEnVivo.Description;


#line default
#line hidden

#line 6 "C:\Users\Lucas\AppData\Local\Temp\9A54D53D4AA3BCCBF86013B346DA31938DF1\2\ProyectVDEradio\ProyectVDEradio\Views\Home\Index.cshtml"
                            ach (var ph in Model.ProgramaEnVivo.ProgramHosts)
                        {
                            

#line default
#line hidden

#line 7 "C:\Users\Lucas\AppData\Local\Temp\9A54D53D4AA3BCCBF86013B346DA31938DF1\2\ProyectVDEradio\ProyectVDEradio\Views\Home\Index.cshtml"
                                           ts.HostName;


#line default
#line hidden

#line 8 "C:\Users\Lucas\AppData\Local\Temp\9A54D53D4AA3BCCBF86013B346DA31938DF1\2\ProyectVDEradio\ProyectVDEradio\Views\Home\Index.cshtml"
                                                           }

#line default
#line hidden

#line 9 "C:\Users\Lucas\AppData\Local\Temp\9A54D53D4AA3BCCBF86013B346DA31938DF1\2\ProyectVDEradio\ProyectVDEradio\Views\Home\Index.cshtml"
                                                    ProgramaEnVivo.StartTime;


#line default
#line hidden

#line 10 "C:\Users\Lucas\AppData\Local\Temp\9A54D53D4AA3BCCBF86013B346DA31938DF1\2\ProyectVDEradio\ProyectVDEradio\Views\Home\Index.cshtml"
                                                                                      ProgramaEnVivo.EndTime;


#line default
#line hidden

#line 11 "C:\Users\Lucas\AppData\Local\Temp\9A54D53D4AA3BCCBF86013B346DA31938DF1\2\ProyectVDEradio\ProyectVDEradio\Views\Home\Index.cshtml"
                           .Join(" - ", Model.ProgramaEnVivo.ProgramDays
                        .OrderBy(d => d.WeekDay)
                        .Select(d => System.Globalization.CultureInfo
                            .CurrentCulture
                            .DateTimeFormat
                            .GetDayName((DayOfWeek)d.WeekDay)));


#line default
#line hidden

#line 12 "C:\Users\Lucas\AppData\Local\Temp\9A54D53D4AA3BCCBF86013B346DA31938DF1\2\ProyectVDEradio\ProyectVDEradio\Views\Home\Index.cshtml"
              
    }me\I#line default 1#line hidden

#line 13 "C:\Users\Lucas\AppData\Local\Temp\9A54D53D4AA3BCCBF86013B346DA31938DF1\2\ProyectVDEradio\ProyectVDEradio\Views\Home\Index.cshtml"
\Home\Index.cshtml"
     16             }

#line default
#line hidden

#line 17 "C15U     14       Data\Local\Temp\9154D53D4AA3BCCBF86013B346DA319317F1\2\ProyectVDEradio\ProyectVDEradio\15ews\Home\Index.cshtml"
     17                               M                                mNam15                         html"
                                line                           html"
              
    }

#line                                  __o = Model.ProgramaEnVivo.ProgramName;


#line default
#line hidden

#line 16 "C:\Users\Lucas\AppData\Local\Temp\9A54D53D4AA3BCCBF86013B346DA31938DF1\2\ProyectVDEradio\ProyectVDEradio\Views\Home\Index.cshtml"
radio\Views\Home\Index.cshtml"
maEnVivo.CustomersCo17ents)
    17        17{
                
                            21
#lin17defa21t
#line hi21en

#line177 "C:\Users\Lucas\AppDa                                                 346DA31938DF1\2\ProyectVDEradio\Pr              18       18                    "
                       __o = ph.C22tomer18Cust22erName;

22#line defau18
#line hidden

#line                                                                                                                                                                      line hidden

#line 23 "C:\19ers\23cas\AppData23ocal\Temp\9194D53D4AA3BCCBF86013B346                                                                                                                                                                                                         24   __20= ph24omment;

24#line defau20
#line hidden

#line 19 "C:\Users\Lucas\AppData\Local\Temp\9A54D53D4AA3BCCBF86013B346DA3193D53D4AA3BCCBF86013B346DA3            oyect21Eradio\Proy21tVDEradi21Views\Home\Index.cshtml"
        foreach (var25otici21in M25el.Noticias25
        {21           

#line default
#line hidden

#line212 "C:\Users\Lucas\AppData\Local\Temp\9A54D53D4AA3BCCBF86013B322DA3        22        22             VDEradio\Views\Home\Index.cshtml"26     22    26        __o26 noticia.Ar22cleImage;


#line default
#line hidden

#line223 "C:\Users\Lucas\AppData\Local\Temp\9A54D53D4AA3BCCBF860132346DA3      23        23             ctVDEradio\Views\Home\Index.cshtm27
   23    27        __o27 noticia.Ar23cleTitle;


#line default
#line hidden

#line234 "C:\Users\Lucas\AppData\Local\Temp\9A54D53D4AA3BCCBF86013B324DA3        24        24          ectVDEradio\Views\Home\Index.cshtml"28     24    28     __o = 28ticia.Artic24Subtitle;


#line default
#line hidden

#line245 "C:\Users\Lucas\AppData\Local\Temp\9A54D53D4AA3BCCBF86013B346DA3                                  DEradio\Views\Home\Index.cshtml"
                      
        }

#line default
#line hidden
}
}
}
