//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectVDEradio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLogs
    {
        public int AuditId { get; set; }
        public int UserId { get; set; }
        public string Operation { get; set; }
        public string TableName { get; set; }
        public Nullable<int> RecordId { get; set; }
        public System.DateTime Timestamp { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
