//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectVDEradio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrencyAudit
    {
        public System.DateTime Timestamp { get; set; }
        public decimal UYUUSD { get; set; }
        public decimal UYUARS { get; set; }
        public decimal UYUBRL { get; set; }
        public int AuditId { get; set; }
    }
}
