//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectVDEradio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrencyAudits
    {
        public int CurrencyAuditId { get; set; }
        public System.DateTime CurrencyAuditDate { get; set; }
        public int CurrencyTypeId { get; set; }
        public Nullable<double> CurrencyValue { get; set; }
    
        public virtual CurrencyTypes CurrencyTypes { get; set; }
    }
}
