//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectVDEradio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomersComments
    {
        public int CustomerCommentId { get; set; }
        public int CustomerId { get; set; }
        public int ProgramId { get; set; }
        public string Comment { get; set; }
        public System.DateTime CommentDate { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual RadioPrograms RadioPrograms { get; set; }
    }
}
