//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectVDEradio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermissionsRoles
    {
        public int PermissionId { get; set; }
        public bool PermissionAddComment { get; set; }
        public bool PermissionAddNews { get; set; }
        public bool PermissionAddRegister { get; set; }
        public bool PermissionAddPrograms { get; set; }
        public bool PermissionAddSponsor { get; set; }
        public int RoleID { get; set; }
    
        public virtual Roles Roles { get; set; }
    }
}
