//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectVDEradio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramHosts
    {
        public int ProgramHostsId { get; set; }
        public int ProgramId { get; set; }
        public int HostId { get; set; }
    
        public virtual Hosts Hosts { get; set; }
        public virtual RadioPrograms RadioPrograms { get; set; }
    }
}
