//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectVDEradio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sponsors
    {
        public int SponsorID { get; set; }
        public string SponsorName { get; set; }
        public string SponsorDescription { get; set; }
        public Nullable<int> SponsorPlan { get; set; }
        public string SponsorImage { get; set; }
    }
}
