//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectVDEradio.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VozDelEsteDBEntities : DbContext
    {
        public VozDelEsteDBEntities()
            : base("name=VozDelEsteDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AuditLogs> AuditLogs { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<CustomersComments> CustomersComments { get; set; }
        public virtual DbSet<Hosts> Hosts { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<ProgramHosts> ProgramHosts { get; set; }
        public virtual DbSet<RadioPrograms> RadioPrograms { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Sponsors> Sponsors { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<ProgramDays> ProgramDays { get; set; }
        public virtual DbSet<CurrencyAudit> CurrencyAudit { get; set; }
        public virtual DbSet<PermissionRole> PermissionRole { get; set; }
        public virtual DbSet<Permissions> Permissions { get; set; }
    }
}
