//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectVDEradio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeatherAudits
    {
        public int WeatherAuditId { get; set; }
        public System.DateTime WeatherAuditDate { get; set; }
        public string WeatherAuditDescription { get; set; }
        public int WeatherAuditIconId { get; set; }
    
        public virtual WeatherIcons WeatherIcons { get; set; }
    }
}
