//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectVDEradio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeatherAudit
    {
        public int WeatherAuditId { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public decimal Temp { get; set; }
        public string Icon { get; set; }
        public string Description { get; set; }
        public int Feels_like { get; set; }
        public int Temp_min { get; set; }
        public int Temp_max { get; set; }
        public System.DateTime Sunrise { get; set; }
        public System.DateTime Sunset { get; set; }
    }
}
